In [64]:
import numpy as np

# create array x
x = np.array([1,2])
z = np.arange(2, 10, dtype=np.float)
k = np.arange(4, 8, 0.16)

In [65]:
print x
print
print z
print
print k

[1 2]

[ 2.  3.  4.  5.  6.  7.  8.  9.]

[ 4.    4.16  4.32  4.48  4.64  4.8   4.96  5.12  5.28  5.44  5.6   5.76
  5.92  6.08  6.24  6.4   6.56  6.72  6.88  7.04  7.2   7.36  7.52  7.68
  7.84]


In [38]:
# print the shape of x

print x.shape
print z.shape
print k.shape


(2,)
(8,)
(25,)


In [39]:
# create a two dimensional array

x.reshape(1,2)
z.reshape(4,2)
k.reshape(5,5)

array([[ 4.  ,  4.16,  4.32,  4.48,  4.64],
       [ 4.8 ,  4.96,  5.12,  5.28,  5.44],
       [ 5.6 ,  5.76,  5.92,  6.08,  6.24],
       [ 6.4 ,  6.56,  6.72,  6.88,  7.04],
       [ 7.2 ,  7.36,  7.52,  7.68,  7.84]])

In [40]:
print x.shape
print z.shape
print k.shape


(2,)
(8,)
(25,)


In [41]:
# create a two dimensional array

x = x.reshape(1,2)
z = z.reshape(4,2)
k = k.reshape(5,5)

In [42]:
# print shape of 2d array

print x.shape
print z.shape
print k.shape

(1, 2)
(4, 2)
(5, 5)


In [43]:
# reshape the array to 2 x 6

a = np.arange(12).reshape((2, 6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [44]:
# reshape the array to 1 x 12

a.reshape((1,12))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [62]:
c = np.array([[0, 1],[2, 3]]);
c

array([[0, 1],
       [2, 3]])

In [63]:
np.transpose(c)   

array([[0, 2],
       [1, 3]])

In [45]:
print x
print
print z
print
print k

[[1 2]]

[[ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]]

[[ 4.    4.16  4.32  4.48  4.64]
 [ 4.8   4.96  5.12  5.28  5.44]
 [ 5.6   5.76  5.92  6.08  6.24]
 [ 6.4   6.56  6.72  6.88  7.04]
 [ 7.2   7.36  7.52  7.68  7.84]]


In [46]:
print x.shape
print z.shape
print k.shape

(1, 2)
(4, 2)
(5, 5)


In [55]:
# Using the Numpy documentation transpose the array

x.T
z.T
k.T


array([[ 4.  ,  4.8 ,  5.6 ,  6.4 ,  7.2 ],
       [ 4.16,  4.96,  5.76,  6.56,  7.36],
       [ 4.32,  5.12,  5.92,  6.72,  7.52],
       [ 4.48,  5.28,  6.08,  6.88,  7.68],
       [ 4.64,  5.44,  6.24,  7.04,  7.84]])

In [56]:
print x
print
print z
print
print k

[[1 2]]

[[ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]]

[[ 4.    4.16  4.32  4.48  4.64]
 [ 4.8   4.96  5.12  5.28  5.44]
 [ 5.6   5.76  5.92  6.08  6.24]
 [ 6.4   6.56  6.72  6.88  7.04]
 [ 7.2   7.36  7.52  7.68  7.84]]


In [57]:
print x.shape
print z.shape
print k.shape

(1, 2)
(4, 2)
(5, 5)


In [52]:
b = np.array([4])
b.shape

(1,)

In [53]:
b

array([4])

In [54]:
b.T

array([4])

In [ ]:
#It's working exactly as it's supposed to. The transpose of a 1D array is still a 1D array! 

In [ ]:
# Create a 3 dimensional array with non-zero values. Research numpy.apply_along_axis. 
# Use numpy.apply_along_axis to reduce axis number 2 by taking the elements along
# the axis number to the power of 3 and summing them up.



In [66]:
import pandas as pd
import numpy as np
import string

In [67]:
# Easy problems

# 1. convert each string from lowercase to uppercase
# [Hint: python strings can be turned to uppercase by appending: .upper(), e.g 'hello'.upper()]
strings = ['black','Yellow','ReD','GreeN','BLUe']


In [68]:
strings = [x.upper() for x in strings]
strings

['BLACK', 'YELLOW', 'RED', 'GREEN', 'BLUE']

In [93]:
# 2. take the numbers in the list and keep only the even numbers
# [Hint: the modulo operator % can be used to calculate the remainder, e.g. 5 % 2 == 1]

numbers = [1,2,3,4,5,6,7,8,9,10]


In [94]:
numbers_e = [n for n in numbers if n%2 == 0]
        
numbers_e

[2, 4, 6, 8, 10]

In [103]:
# 3. convert to 'v' if a character is a vowel and 'c' if a consonant, otherwise convert to '?'

characters = ['a','f',None,'k','l','1',12,'e','e',-1,'i','b','p']
alphabet = list(string.ascii_lowercase)
vowels = ['a','e','i','o','u']

In [104]:
# for c in characters:
#     if c in vowels:
#         c = 'v'
#     elif c in alphabet:
#         c = 'c'
#     else:
#         c = '?'
        
characters_trans = ['v' if c in vowels else 'c' if c in alphabet else '?' for c in characters]
characters_trans

['v', 'c', '?', 'c', 'c', '?', '?', 'v', 'v', '?', 'v', 'c', 'c']

In [105]:
# Medium problems
# 4. calculate the means of the numbers in each list that lie between 0 and 100 (inclusive)

number_sets = [[1,50,-40,20,90], [1004,1002,101,-90,40,34], [-1,-2,34,55,77,109]]


In [114]:
for sets in number_sets:
    for num in sets:
        av = []
        print num
        if 0 <= num >= 100:
            av.append(num)
            print av
            #         np.mean(av)

1
50
-40
20
90
1004
[1004]
1002
[1002]
101
[101]
-90
40
34
-1
-2
34
55
77
109
[109]


In [ ]:
5. for each string in each list, if the index of the strings is even, join them like: 'item1 item2'. Otherwise join them like: 'item2 item1'.

strings1 = ['alpha','bravo','charlie','delta']
strings2 = ['echo','foxtrot','golf','hotel']


In [ ]:
6. create a pandas dataframe from the columns and associated values where each column is the first five multiples of the values:

columns = ['five','seven','twelve']
values = [5, 7, 12]
multiples = [1, 2, 3, 4, 5]
Hard problems


In [ ]:
7. manually calculate the median of the first n numbers (from list "N") in list "X"

N = [12, 5, 6, 8, 10]
X = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [ ]:
8. combine into a flat list:
iterate the elements of one list
iteratively multiply by them by the elements in the second list
then iteratively subtract the elements in a third list
e.g:
a = [1,2]
b = [0,1]
c = [1,2]
output = [0,0,0,-1,0,0,1,0]

a = [9,7,5]
b = [10,5,1]
c = [1,2,3]

In [126]:
import pandas as pd

nums = np.arange(0,101,1)

fb_track = pd.DataFrame(nums, columns=['nums'])

def fb_table(num_val):
    if num_val % 15 == 0:
        return "FizzBuzz"
    if num_val % 3 == 0:
        return "Fizz"
    if num_val % 5 == 0:
        return "Buzz"
    else:
        return num_val


fb_track['FB_check'] = fb_track['nums'].apply(fb_table)

In [127]:
fb_track['FB_check'] = fb_track.applymap(fb_table)
fb_track

nums  FB_check
0       0  FizzBuzz
1       1         1
2       2         2
3       3      Fizz
4       4         4
5       5      Buzz
6       6      Fizz
7       7         7
8       8         8
9       9      Fizz
10     10      Buzz
11     11        11
12     12      Fizz
13     13        13
14     14        14
15     15  FizzBuzz
16     16        16
17     17        17
18     18      Fizz
19     19        19
20     20      Buzz
21     21      Fizz
22     22        22
23     23        23
24     24      Fizz
25     25      Buzz
26     26        26
27     27      Fizz
28     28        28
29     29        29
..    ...       ...
71     71        71
72     72      Fizz
73     73        73
74     74        74
75     75  FizzBuzz
76     76        76
77     77        77
78     78      Fizz
79     79        79
80     80      Buzz
81     81      Fizz
82     82        82
83     83        83
84     84      Fizz
85     85      Buzz
86     86        86
87     87      Fizz
88     88        88
89     89        89
90     90  FizzBuzz
91     91        91
92     92        92
93     93      Fizz
94     94        94
95     95      Buzz
96     96      Fizz
97     97        97
98     98        98
99     99      Fizz
100   100      Buzz

[101 rows x 2 columns]

In [150]:
# Write a function that takes a string and returns True if the string's parentheses are balanced, False if they are not.
from pythonds.basic.stack import Stack


def count_check(string_of_parenth):
    
    counter = Stack()
    
    for single in string_of_parenth:
        if single == '(':
            counter += 1
        elif single == ')':
            counter -= 1
        else:
            print 'something went wrong'

            
    if counter == 0:
        return True
    else:
        return False
    


In [151]:
count_check('(()()))(()')

True